In [1]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the resulting matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
